### ISSUE TITLE
New Layers Panel and Pages Panel UI broke the dark visual

### ISSUE THREAD

**Issue by renatocarvalho** [PaperTiger/figma-plugins#1]
You are probably aware of the issue. But the new update that Figma did yesterday on the Layers Panel and Pages Panel UI broke a few things on the dark theme. Sharing with you guys. Cheers!

<img width="617" alt="screen shot 2018-04-05 at 15 16 20" src="https://user-images.githubusercontent.com/16294/38384035-791e1650-38e4-11e8-892d-582f613b82be.png">

<img width="612" alt="screen shot 2018-04-05 at 15 16 24" src="https://user-images.githubusercontent.com/16294/38384036-794924b2-38e4-11e8-86df-8feb6c97e072.png">

**Comment by nadszeg** [comment]
Same on Windows 10 - also the rulers are white too: 
![image](https://user-images.githubusercontent.com/23207232/39316994-d49631c4-497a-11e8-9457-335c46642e3c.png)

**Comment by renatocarvalho** [comment]
Is the source code shared here? So we can help with the fixes? Any update here would be awesome because I love the Dark Theme :)

**Comment by mirkosantangelo** [comment]
Hey @renatocarvalho!

Sorry I miss your message! A new and improved version of the plugin is going to be released soon! ;) Stay tuned!

**Comment by mirkosantangelo** [comment]
@nadszeg Unfortunately I've found no way to change the rulers style.

**Comment by nadszeg** [comment]
Oh okay, thanks for looking into it! :) I'm hyped for the next update!
