### ISSUE TITLE
Comments panel contrast

### ISSUE THREAD

**Issue by Alexfrits** [PaperTiger/figma-plugins#2]
Hi,

I'm a big fan of this dark UI plugin and I started using it today.
I know this is still an early version and you might not have styled the whole interface, so I'll try to help as much as I can.

The comments panel is hardly usable with the dark UI:
![figjet_dark-ui_comments-panel_issue](https://user-images.githubusercontent.com/9515079/39037777-cfa61c36-4481-11e8-8c4e-1ac957ea715c.png)

It's not blocking, because redability is better when you hover the item (even if it breaks the dark theme) and I don't _read_ comments from the sidebar, but it could be imporved. :)

I'm using:
- the desktop app
- on Windows 10
- with the devtools snippet "hack"

P.S. I would be glad to contribute directly to the code, but the snippet you shared on this repo is not the source, is it?

Alex

**Comment by mirkosantangelo** [comment]
Hi @Alexfrits! Thanks for the report and sorry for the late reply!

A new and improved version of the plugin is going to be released soon! ;) Stay tuned!
