### ISSUE TITLE
Provide non-obfuscated code

### ISSUE THREAD

**Issue by tellaho** [PaperTiger/figma-plugins#3]
I understand the merit of trying to compress it, but just about anything could be tucked in there.

It'd be great if you provided the pre-compiled code.

**Comment by mirkosantangelo** [comment]
The compression came with the need of simplifying the process of activating the plugin for the desktop users, since they have to paste the full script every time. 

There's no harmful code, nor trackers of any sort. 

Btw, a new version based on React will be released in the future.

**Comment by tellaho** [comment]
It's free plug-in, it's your repo. Do as you wish. ¯\_(ツ)_/¯
