### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by cdes** [PaperTiger/figma-plugins#4]
First of all, let me just take a moment to highlight your great work! Well done!
I have a question, can you please add a license to this repo (preferably MIT)?

Wanna know why?

I was intrigued to see how you made it work, and to my surprise it's neat.

By utilizing your structure, I created a BATCH RENAME option that actually works.  However, I'm unable to share it because your repo is missing a license.

**Comment by mirkosantangelo** [comment]
Hi Cdes, we're evaluating this internally, but for now there's no plan to make the source open and available for redistribution. I'll keep you posted if something new happen. 

Feel free to shoot us a mail if you have some question. At team@papertiger.com Thanks!
