### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by flsqz** [PaperTiger/figma-plugins#6]
Comments on right inspector still light

**Comment by redview13** [comment]
![image](https://user-images.githubusercontent.com/32819396/43083247-bbf7a6ac-8e9e-11e8-9054-cc91b6dc58f2.png)
![image](https://user-images.githubusercontent.com/32819396/43083269-caf1c764-8e9e-11e8-8e85-7ad1b848c1e9.png)
![image](https://user-images.githubusercontent.com/32819396/43083318-e4a3a6a0-8e9e-11e8-9d67-f12bf5899044.png)

**Comment by flsqz** [comment]
I mean the highlighted comment state
![comment](https://user-images.githubusercontent.com/7523759/43086869-b37bc8d2-8e9e-11e8-9f79-46adbbdefec3.gif)

**Comment by mirkosantangelo** [comment]
Thanks for the report guys. We'll publish a fix soon.

**Comment by mirkosantangelo** [comment]
This issue has been solved in 2.0.1
