### ISSUE TITLE
Official version and Dark Theme version

### ISSUE THREAD

**Issue by redview13** [PaperTiger/figma-plugins#7]
На какой версии официального клиента основан ваш? В меню Figma→About информация представлена по другому.
Это важно, потому как Beta версия официального клиента работает в пространстве sRGB.
-
On which version of the official client is yours based? In the Figma → About menu, information is presented in a different way.
This is important, because Beta version of the official client works in the sRGB space.

Dark
![image](https://user-images.githubusercontent.com/32819396/43071014-1a0b1244-8e7a-11e8-93b4-3fa3b57944a6.png)

Official
![image](https://user-images.githubusercontent.com/32819396/43071036-26a2d5a0-8e7a-11e8-81ea-6572af417c95.png)

**Comment by mirkosantangelo** [comment]
The panel is based on the latest Figma client app available as Beta. The sRBG issue has been fixed on this version.

**Comment by redview13** [comment]
Excellent! Thank you!
