### ISSUE TITLE
Text color of renamed layer is too light

### ISSUE THREAD

**Issue by anton-liubushkin** [PaperTiger/figma-plugins#8]
The name of the renamed layer cannot be read. The text color is too light.

![Screenshot](https://user-images.githubusercontent.com/5649032/43120029-f368ef16-8f42-11e8-9080-d779583784eb.png)

**Comment by mirkosantangelo** [comment]
Yup spotted this as well today! Thanks for the report! Fix coming :)

**Comment by mirkosantangelo** [comment]
This issue has been solved in 2.0.1
